# 官方文档：https://wiki.metacubex.one/
#
# 以 '#' 或 '//' 开头的配置文件行为注释行
#
# Mihomo Version ≥ 1.8.10

p: &p {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 1800, timeout: 5000}}
proxy-providers:
  Subscribe: 
    url: 
    <<: *p
    #override: 
      #additional-prefix: "节点前缀"
      #additional-suffix: "节点后缀"
  #Subscribe2: 
    #url: 
    #<<: *p
    #override: 
      #additional-prefix: "节点前缀"
      #additional-suffix: "节点后缀"
  #Subscribe3: 
    #url: 
    #<<: *p
    #override: 
      #additional-prefix: "节点前缀"
      #additional-suffix: "节点后缀"

mixed-port: 7893
tcp-concurrent: true
allow-lan: true
ipv6: true
log-level: info
unified-delay: true
find-process-mode: strict

geodata-mode: true
geox-url:
  geoip: "https://git.repcz.link/raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat"
  geosite: "https://git.repcz.link/github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://git.repcz.link/raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
  asn: "https://git.repcz.link/raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-ASN.mmdb"

profile: { store-selected: true, store-fake-ip: false }
sniffer: { enable: true, sniff: { HTTP: { ports: [80], override-destination: true }, TLS: { ports: [443, 8443] }, QUIC: { ports: [443, 8443] } } }

tun:
  enable: true
  stack: system
  dns-hijack: [any:53]
        
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  listen: :1053
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['+.lan', '*', '+.local', '+.cmpassport.com', 'id6.me', 'open.e.189.cn', 'mdn.open.wo.cn', 'opencloud.wostore.cn', 'auth.wosms.cn', '+.10099.com.cn', '+.msftconnecttest.com', '+.msftncsi.com', 'lancache.steamcontent.com']
  nameserver: [223.5.5.5, 119.29.29.29]
  proxy-server-nameserver: [223.5.5.5, 119.29.29.29]

# 锚点参数
pg: &pg {type: select, proxies: [DIRECT, 节点选择, 香港节点, 台湾节点, 日本节点, 狮城节点, 美国节点]}
select: &select {type: select, include-all: true, exclude-filter: "流量|重置|到期|官网|网址|文档"}
url-test: &url-test {type: url-test, url: https://www.gstatic.com/generate_204, interval: 300, tolerance: 0, include-all: true}
c: &c {type: http, behavior: classical, format: text, interval: 86400}

proxy-groups:
  - {name: 节点选择, <<: *select, proxies: [香港节点, 台湾节点, 日本节点, 狮城节点, 美国节点], icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Rocket.png}
  - {name: 国外网站, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Global.png}
  - {name: Emby, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Emby.png}
  - {name: 云盘服务, <<: *select, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/iCloud.png}
  - {name: 电报消息, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Telegram.png}
  - {name: 推特消息, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Twitter.png}
  - {name: AI, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/AI.png}
  - {name: E-Hentai, <<: *pg, icon: https://github.com/lige47/QuanX-icon-rule/raw/main/icon/04ProxySoft/exhentai.png}
  - {name: 游戏平台, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Game.png}
  - {name: 哔哩哔哩, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/bilibili.png}
  - {name: 巴哈姆特, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Bahamut.png}
  - {name: 谷歌服务, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Google_Search.png}
  - {name: 微软服务, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Microsoft.png}
  - {name: 数币平台, <<: *pg, icon: https://github.com/lige47/QuanX-icon-rule/raw/main/icon/04ProxySoft/Bitcoin.png}
  - {name: 仅限日本, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/JP.png}
  - {name: 排除日本, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Reject.png}
  - {name: 兜底分流, <<: *pg, icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Final.png}
  - {name: 香港节点, <<: *url-test, filter: "(?i)🇭🇰|香港|(\\b(HK|Hong)\\b)", icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Hong_Kong.png}
  - {name: 台湾节点, <<: *url-test, filter: "(?i)🇨🇳|🇹🇼|台湾|(\\b(TW|Tai|Taiwan)\\b)", icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Taiwan.png}
  - {name: 日本节点, <<: *url-test, filter: "(?i)🇯🇵|日本|东京|(\\b(JP|Japan)\\b)", icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Japan.png}
  - {name: 狮城节点, <<: *url-test, filter: "(?i)🇸🇬|新加坡|狮|(\\b(SG|Singapore)\\b)", icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Singapore.png}
  - {name: 美国节点, <<: *url-test, filter: "(?i)🇺🇸|美国|洛杉矶|圣何塞|(\\b(US|United States)\\b)", icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/United_States.png}

rule-providers:
  Direct: {<<: *c, url: https://github.com/Sofzya/Clash/raw/main/Rules/Direct.list}
  CloudDrive: {<<: *c, url: https://github.com/Sofzya/Clash/raw/main/Rules/CloudDrive.list}
  MEGA: {<<: *c, url: https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/MEGA/MEGA.list}
  OutJP: {<<: *c, url: https://github.com/Sofzya/Clash/raw/main/Rules/OutJP.list}
  OnlyJP: {<<: *c, url: https://github.com/Sofzya/Clash/raw/main/Rules/OnlyJP.list}
  Proxy: {<<: *c, url: https://github.com/Sofzya/Clash/raw/main/Rules/Proxy.list}
  MoreEmby: {<<: *c, url: https://github.com/Sofzya/Clash/raw/main/Rules/MoreEmby.list}
  Emby: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Emby.list}
  Telegram: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Telegram.list}
  Twitter: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Twitter.list}
  MoreAI: {<<: *c, url: https://github.com/Sofzya/Clash/raw/main/Rules/MoreAI.list}
  AI: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/AI.list}
  E-Hentai: {<<: *c, url: https://github.com/powerfullz/override-rules/raw/main/ruleset/EHentai.list}
  Steam: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Steam.list}
  Epic: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Epic.list}
  BiliBili: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Bilibili.list}
  Bahamut: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Bahamut.list}
  YouTube: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/YouTube.list}
  Google: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Google.list}
  Github: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Github.list}
  OneDrive: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/OneDrive.list}
  Microsoft: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Microsoft.list}
  OKX: {<<: *c, url: https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/OKX/OKX.list}
  Binance: {<<: *c, url: https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Binance/Binance.list}
  Bybit: {<<: *c, url: https://github.com/Sofzya/Clash/raw/main/Rules/Bybit.list}
  Lan: {<<: *c, url: https://github.com/Repcz/Tool/raw/X/mihomo/Rules/Lan.list}

rules:
  - RULE-SET,Direct,DIRECT
  - RULE-SET,CloudDrive,云盘服务
  - RULE-SET,MEGA,云盘服务
  - RULE-SET,OutJP,排除日本
  - RULE-SET,OnlyJP,仅限日本
  - RULE-SET,Proxy,国外网站
  - RULE-SET,MoreEmby,Emby
  - RULE-SET,Emby,Emby
  - RULE-SET,Telegram,电报消息
  - RULE-SET,Twitter,推特消息
  - RULE-SET,MoreAI,AI
  - RULE-SET,AI,AI
  - RULE-SET,E-Hentai,E-Hentai
  - RULE-SET,Steam,游戏平台
  - RULE-SET,Epic,游戏平台
  - RULE-SET,BiliBili,哔哩哔哩
  - RULE-SET,Bahamut,巴哈姆特
  - RULE-SET,YouTube,谷歌服务
  - RULE-SET,Google,谷歌服务
  - RULE-SET,Github,微软服务
  - RULE-SET,OneDrive,微软服务
  - RULE-SET,Microsoft,微软服务
  - RULE-SET,OKX,数币平台
  - RULE-SET,Binance,数币平台
  - RULE-SET,Bybit,数币平台
  - RULE-SET,Lan,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,兜底分流